products/urls.py
from django.urls import path
from products.views import products, reserve_computer, reserve_delete

app_name = 'products'

urlpatterns = [
    path('', products, name='index'),
    path('computers_list/<int:computer_name>/', reserve_computer, name='reserve_computer'),
    path('computers_list/', reserve_delete, name='reserve_delete'),
]

reservation/urls.py
from django.contrib import admin
from django.urls import path, include

from products.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
]

users/urls.py
from django.urls import path
from users.views import login, registration, cabinet, logout

app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),
    path('registration/', registration, name='registration'),
    path('cabinet/', cabinet, name='cabinet'),
    path('logout/', logout, name='logout'),
]

products/models.py
from django.db import models

from users.models import User


# Create your models here.

#class UsersInfo(models.Model):
 #   email = models.EmailField(null=True)
 #   user_name = models.CharField(max_length=128)
  #  password = models.CharField(max_length=128)
 #   def __str__(self):
   #     return self.user_name


class Computers(models.Model):
    computer_name = models.CharField(max_length=128)
    availability_status = models.BooleanField(default=True)

    def __str__(self):
        return self.computer_name


class Reservations(models.Model):
    user_id = models.ForeignKey(to=User, on_delete=models.CASCADE)
    computer_id = models.ForeignKey(to=Computers, on_delete=models.CASCADE)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Пользователь: {self.user_id} | Компьютер #: {self.computer_id}'

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    pass

users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from users.models import User
from django import forms
class UserLoginForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите имя пользователя'}))
    password = forms.CharField(label='Пароль',
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Введите пароль'}))
    class Meta:
        model = User
        fields = ('username', 'passwordП')

class UserRegisterForm(UserCreationForm):
    username = forms.CharField(label='Логин',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите имя пользователя'}))
    password1 = forms.CharField(label='Пароль',
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Введите пароль'}))
    password2 = forms.CharField(label='Подтвердите пароль',
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Подтвердите пароль'}))
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')

class UserProfileForm(UserChangeForm):
    first_name = forms.CharField(label='Имя',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Имя', 'readonly': True}), required=False)
    last_name = forms.CharField(label='Фамилия',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Фамилия', 'readonly': True}), required=False)
    username = forms.CharField(label='Логин',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите имя пользователя', 'readonly': True}))
    password = forms.CharField(label= 'Ваш пароль',
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Пароль'}))
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'password')

products/views.py
from django.shortcuts import render, HttpResponseRedirect
from products.models import Computers, Reservations
from users.models import User

# Create your views here.
def index(request):
    context = {'title': 'Главная',
               }
    return render(request, 'products/index.html', context)

def products(request):
    context = {
        'title': 'Забронировать',
        'reservations': Reservations.objects.filter(user_id=request.user),
    }
    return render(request, 'products/products.html', context)

def reserve_computer(request, computer_name):
    computer_id = Computers.objects.get(id=computer_name)
    user = request.user
    reservation = Reservations.objects.filter(user_id=user, computer_id=computer_id)

    if not reservation.exists() and not Reservations.objects.filter(computer_id=computer_id).exists():
        Reservations.objects.create(user_id=request.user, computer_id=computer_id)
        alert = f"Вы успешно забронировали компьютер №{computer_id}"
    else:
        alert = "Компьютер уже забронирован"


    context = {
        'has_reservation': True,
        'alert_message': alert,
    }

    return render(request, 'products/products.html', context)


def reserve_delete(request):
    if request.method == 'POST':
        computer_id = request.POST.get('computer_id')
        user = request.user
        reservation = Reservations.objects.filter(user_id=user, computer_id=computer_id).first()
        alert2 = f"Вы не можете отменить бронь компьютера №{computer_id}"
        if reservation:
            reservation.delete()
            alert2 = f"Вы отменили бронь компьютера №{computer_id}"



        context = {
            'has_reservation': True,
            'alert_message2': alert2,
        }

    return render(request, 'products/products.html', context)

users/views.py
from django.shortcuts import render, HttpResponseRedirect
from users.models import User
from users.forms import UserLoginForm, UserRegisterForm, UserProfileForm
from django.contrib import auth, messages
from django.urls import reverse

# Create your views here.
def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('index'))
    else:
        form = UserLoginForm()
    context = {'title': 'Вход',
               'form': form,
               }
    return render(request, 'users/login.html', context)

def registration(request):
    if request.method == 'POST':
        form = UserRegisterForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Вы успешно зарегистрировались!')
            return HttpResponseRedirect(reverse('users:login'))
    else:
        form = UserRegisterForm()
    context = {'title': 'Регистрация',
               'form': form,
               }
    return render(request, 'users/registration.html', context)

def cabinet(request):
    if request.method == 'POST':
        form = UserProfileForm(instance=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('users:cabinet'))
        else:
            print(form.errors)
    else:
        form = UserProfileForm(instance=request.user)
    context = {'title': 'Личный кабинет',
               'form': form,
               }
    return render(request, 'users/cabinet.html', context)

def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('index'))

products/templates/products/Cabinet.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/Cabinet.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <title>Main</title>
</head>
<body>
    <header>
        <nav>
            <ul class="site-navigation">
                <div class="header-title">
                    <li class="site-navigation-title">
                        <a class="site-navigation-link" href="index">WIS</a>
                    </li>
                </div>
                <div class="header-buttons">
                    <li class="site-navigation-item">
                        <a class="site-navigation-link" href="AboutUs">О нас</a>
                    </li>
                    <li class="site-navigation-item">
                        <a class="site-navigation-link" href="Cabinet">Личный кабинет</a>
                    </li>
                </div>
              </ul>
        </nav> 
    </header>
    <main class="general">
        <section>
            <p>a</p>
            <p>a</p>
            <p>a</p>
            <p>a</p>
            <p>a</p>
            <p>a</p>
            <p>a</p>
            <p>a</p>
            <p>a</p>
            <p>a</p>
            <p>a</p>
            <p>a</p>
            <p>a</p>
            <p>Шикарный текст про нас</p>
            <p>a</p>
            <p>a</p>
            <p>a</p>
            <p>a</p>
            <p>a</p>
            <p>a</p>
            <p>a</p>
            <p>a</p>
            <p>a</p>
            <p>a</p>
            <p>a</p>
            <p>a</p>
            <p>a</p>
            <p>a</p>
        </section>
    </main>
    <footer>
        <div class="contacts-info">
            <h3 class="footer-contact-title">Контакты</h3>
            <div class="people-contacts">
                <div class="footer-contact">
                    <p class="footer-text">https://vk.com/tochnonedayn</p>
                    <p class="footer-text">https://t.me/JKanidy</p>
                    <p class="footer-text">jorakanidi@gmail.com</p>
                </div>
                <div class="footer-contact">
                    <p class="footer-text">https://vk.com/chto_nado_t0</p>
                    <p class="footer-text">https://t.me/chto_nado_to1</p>
                    <p class="footer-text">Caverly228@gmail.com</p>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>

products/templates/products/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block css %}{% endblock %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    {% block title %}{% endblock %}
</head>
<body>
    <header>
        <nav>
            <ul class="site-navigation">
                <div class="header-title">
                    <li class="site-navigation-title">
                        <a class="site-navigation-link" href="{% url 'index' %}">2G</a>
                    </li>
                </div>
                <div class="header-buttons">
                {% if user.is_authenticated %}
                    <li class="site-navigation-item">
                        <a class="site-navigation-link" href="{% url 'users:cabinet' %}">Личный кабинет</a>
                    </li>
                    <li class="site-navigation-item">
                        <a class="site-navigation-link" href="{% url 'users:logout' %}">Выйти</a>
                    </li>
                    {% if user.is_superuser or user.is_staff %}
                     <li class="site-navigation-item">
                        <a class="site-navigation-link" href="{% url 'admin:index' %}">Админ панель</a>
                    </li>
                {% endif %}
                    {% else %}
                        <li class="site-navigation-item">
                            <a class="site-navigation-link" href="{% url 'users:login' %}">Войти</a>
                        </li>
                </div>
                {% endif %}
              </ul>
        </nav>  
    </header>
    <main class="general">
        {% block main %}{% endblock %}
    </main>
    <footer>
        <div class="contacts-info">
            <h3 class="footer-contact-title">Контакты</h3>
            <div class="people-contacts">
                <div class="footer-contact">
                    <p class="footer-text">https://vk.com/tochnonedayn</p>
                    <p class="footer-text">https://t.me/JKanidy</p>
                    <p class="footer-text">jorakanidi@gmail.com</p>
                </div>
                <div class="footer-contact">
                    <p class="footer-text">https://vk.com/chto_nado_t0</p>
                    <p class="footer-text">https://t.me/chto_nado_to1</p>
                    <p class="footer-text">Caverly228@gmail.com</p>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>

products/templates/products/cabinet.html
{% extends 'products/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/cabinet.css' %}">
{% endblock %}

{% block title %}
    <title>{{ title }}</title>
{% endblock %}

{% block main %}
    1
{% endblock %}

products/templates/products/computers_list.html
{% load static %}

<div class="comp-room-container">
    <img class="comp-room" src="{% static 'img/computers-room.png' %}" alt="Компьютеры">
</div>

<script>
    {% if alert_message %}
        alert("{{ alert_message }}");
    {% endif %}

    {% if alert_message2 %}
        alert("{{ alert_message2 }}");
    {% endif %}
</script>

    <div class="title-container">
        <h1 class="comp-title">Выберите компьютер, который хотите забронировать</h1>
    </div>

<p>
<div class="buttons-inline">
<form action="{% url 'products:reserve_computer' computer_name=1 %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Забронировать компьютер 1">
</form>
</div>
{% if has_reservation == True %}
<div class="buttons-inline">
<form method="post" action="{% url 'products:reserve_delete' %}">
    {% csrf_token %}
    <input type="hidden" name="computer_id" value="{{ 1 }}">
    <button type="submit">Удалить бронирование</button>
</form>
</div>
{% endif %}
</p>

<p>
<div class="buttons-inline">
<form action="{% url 'products:reserve_computer' computer_name=2 %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Забронировать компьютер 2">
</form>
</div>
{% if has_reservation == True %}
<div class="buttons-inline">
<form method="post" action="{% url 'products:reserve_delete' %}">
    {% csrf_token %}
    <input type="hidden" name="computer_id" value="{{ 2 }}">
    <button type="submit">Удалить бронирование</button>
</form>
</div>
{% endif %}
</p>

<p>
<div class="buttons-inline">
<form action="{% url 'products:reserve_computer' computer_name=3 %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Забронировать компьютер 3">
</form>
</div>
{% if has_reservation == True %}
<div class="buttons-inline">
<form method="post" action="{% url 'products:reserve_delete' %}">
    {% csrf_token %}
    <input type="hidden" name="computer_id" value="{{ 3 }}">
    <button type="submit">Удалить бронирование</button>
</form>
</div>
{% endif %}
</p>

<p>
<div class="buttons-inline">
<form action="{% url 'products:reserve_computer' computer_name=4 %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Забронировать компьютер 4">
</form>
</div>
{% if has_reservation == True %}
<div class="buttons-inline">
<form method="post" action="{% url 'products:reserve_delete' %}">
    {% csrf_token %}
    <input type="hidden" name="computer_id" value="{{ 4 }}">
    <button type="submit">Удалить бронирование</button>
</form>
</div>
{% endif %}
</p>

<p>
<div class="buttons-inline">
<form action="{% url 'products:reserve_computer' computer_name=5 %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Забронировать компьютер 5">
</form>
</div>
{% if has_reservation == True %}
<div class="buttons-inline">
<form method="post" action="{% url 'products:reserve_delete' %}">
    {% csrf_token %}
    <input type="hidden" name="computer_id" value="{{ 5 }}">
    <button type="submit">Удалить бронирование</button>
</form>
</div>
{% endif %}
</p>

<p>
<div class="buttons-inline">
<form action="{% url 'products:reserve_computer' computer_name=6 %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Забронировать компьютер 6">
</form>
</div>
{% if has_reservation == True %}
<div class="buttons-inline">
<form method="post" action="{% url 'products:reserve_delete' %}">
    {% csrf_token %}
    <input type="hidden" name="computer_id" value="{{ 6 }}">
    <button type="submit">Удалить бронирование</button>
</form>
</div>
{% endif %}
</p>

<p>
<div class="buttons-inline">
<form action="{% url 'products:reserve_computer' computer_name=7 %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Забронировать компьютер 7">
</form>
</div>
{% if has_reservation == True %}
<div class="buttons-inline">
<form method="post" action="{% url 'products:reserve_delete' %}">
    {% csrf_token %}
    <input type="hidden" name="computer_id" value="{{ 7 }}">
    <button type="submit">Удалить бронирование</button>
</form>
</div>
{% endif %}
</p>

<p>
<div class="buttons-inline">
<form action="{% url 'products:reserve_computer' computer_name=8 %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Забронировать компьютер 8">
</form>
</div>
{% if has_reservation == True %}
<div class="buttons-inline">
<form method="post" action="{% url 'products:reserve_delete' %}">
    {% csrf_token %}
    <input type="hidden" name="computer_id" value="{{ 8 }}">
    <button type="submit">Удалить бронирование</button>
</form>
</div>
{% endif %}
</p>

<p>
<div class="buttons-inline">
<form action="{% url 'products:reserve_computer' computer_name=9 %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Забронировать компьютер 9">
</form>
</div>
{% if has_reservation == True %}
<div class="buttons-inline">
<form method="post" action="{% url 'products:reserve_delete' %}">
    {% csrf_token %}
    <input type="hidden" name="computer_id" value="{{ 9 }}">
    <button type="submit">Удалить бронирование</button>
</form>
</div>
{% endif %}
</p>

<p>
<div class="buttons-inline">
<form action="{% url 'products:reserve_computer' computer_name=10 %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Забронировать компьютер 10">
</form>
</div>
{% if has_reservation == True %}
<div class="buttons-inline">
<form method="post" action="{% url 'products:reserve_delete' %}">
    {% csrf_token %}
    <input type="hidden" name="computer_id" value="{{ 10 }}">
    <button type="submit">Удалить бронирование</button>
</form>
</div>
{% endif %}
</p>

products/templates/products/index.html
{% extends 'products/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link rel="icon" href="{% static 'img/computer-mouse.ico' %}" type="image/x-icon">
{% endblock %}

{% block title %}
    <title>{{ title }}</title>
{% endblock %}

{% block main %}
    {% if user.is_authenticated %}
        <p class="main-text"> 2G - это крутой компьютерный клуб, <br>который предлагает уникальное пространство для геймеров и тех,<br> кто ценит высококачественный игровой опыт. Клуб оснащен самым современным оборудованием и высокоскоростным <br> интернетом 2G, чтобы обеспечить непревзойденную производительность в играх. От уютной атмосферы до отличного обслуживания,</p>
        <p class="main-text"><a class="main-link" href="{% url 'products:index' %}">Забронировать💻</a></p>
        <p class="main-text">2G создает идеальные условия для игрового опыта на высшем уровне не только для постоянных клиентов, но и для новоприбывших. <br> Здесь вы найдете единомышленников, готовых поделиться опытом и участвовать в захватывающих мероприятиях. <br> 2G - это не просто клуб, это центр геймерской культуры, где каждый <br> найдет что-то особенное для себя.</p>
    {% else %}
        <p class="main-text"> 2G - это крутой компьютерный клуб, <br>который предлагает уникальное пространство для геймеров и тех,<br> кто ценит высококачественный игровой опыт. Клуб оснащен самым современным оборудованием и высокоскоростным <br> интернетом 2G, чтобы обеспечить непревзойденную производительность в играх. От уютной атмосферы до отличного обслуживания,</p>
        <p class="main-text">Сначала вам нужно<span>&nbsp;</span><a class="main-link" href="{% url 'users:login' %}">войти🚪</a></p>
        <p class="main-text">2G создает идеальные условия для игрового опыта на высшем уровне не только для постоянных клиентов, но и для новоприбывших. <br> Здесь вы найдете единомышленников, готовых поделиться опытом и участвовать в захватывающих мероприятиях. <br> 2G - это не просто клуб, это центр геймерской культуры, где каждый <br> найдет что-то особенное для себя.</p>
    {% endif %}  
{% endblock %}

products/templates/products/products.html
{% extends 'products/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/products.css' %}">
    <link rel="stylesheet" href="{% static 'css/computers-list.css' %}">
    <link rel="icon" href="{% static 'img/computer-mouse.ico' %}" type="image/x-icon">
{% endblock %}

{% block title %}
    <title>{{ title }}</title>
{% endblock %}

{% block main %}
    {% include 'products/computers_list.html' %}
{% endblock %}

users/templates/users/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block css %}{% endblock %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    {% block title %}{% endblock %}
</head>
<body>
    <header>
        <nav>
            <ul class="site-navigation">
                <div class="header-title">
                    <li class="site-navigation-title">
                        <a class="site-navigation-link" href="{% url 'index' %}">2G</a>
                    </li>
                </div>
                <div class="header-buttons">
                {% if user.is_authenticated %}
                    <li class="site-navigation-item">
                        <a class="site-navigation-link" href="{% url 'users:cabinet' %}">Личный кабинет</a>
                    </li>
                    <li class="site-navigation-item">
                        <a class="site-navigation-link" href="{% url 'users:logout' %}">Выйти</a>
                    </li>
                    {% if user.is_superuser or user.is_staff %}
                     <li class="site-navigation-item">
                        <a class="site-navigation-link" href="{% url 'admin:index' %}">Админ панель</a>
                    </li>
                {% endif %}    
                    {% else %}
                        <li class="site-navigation-item">
                            <a class="site-navigation-link" href="{% url 'users:login' %}">Войти</a>
                        </li>
                </div>
                {% endif %}
              </ul>
        </nav> 
    </header>
    <main class="general">
        {% block main %}{% endblock %}
    </main>
    <footer>
        {% block footer %}{% endblock %}
    </footer>
</body>
</html>

users/templates/users/cabinet.html
{% extends 'users/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/cabinet.css' %}">
    <link rel="icon" href="{% static 'img/computer-mouse.ico' %}" type="image/x-icon">
{% endblock %}

{% block title %}
    <title>{{ title }}</title>
{% endblock %}

{% block main %}
    <div class="cabinet">
        <form action=" {% url 'users:cabinet' %}" method="post">
            {% csrf_token %}
            {{ form.as_div }}
        </form>
    </div>
{% endblock %}

users/templates/users/login.html
{% extends 'users/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <link rel="icon" href="{% static 'img/computer-mouse.ico' %}" type="image/x-icon">
{% endblock %}

{% block title %}
    <title>{{ title }}</title>
{% endblock %}

{% block main %}
    <div class="login">
        <form action="{% url 'users:login' %}" method="post">
            {% csrf_token %}
            {% for message in messages %}
                {{ message }}
            {% endfor %}
            {{ form.as_p }}
        <input type="submit" value="Авторизоваться">
        <a href="{% url 'users:registration' %}">Нет аккаунта?</a>
        </form>
    </div>
{% endblock %}


{#{% if form.non_field_errors %}#}
{#        {{ form.non_field_errors }}#}
{#    {% endif %}#}

users/templates/users/registration.html
{% extends 'users/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/registration.css' %}">
    <link rel="icon" href="{% static 'img/computer-mouse.ico' %}" type="image/x-icon">
{% endblock %}

{% block title %}
    <title>{{ title }}</title>
{% endblock %}

{% block main %}
    <div class="registration">
        <form action=" {% url 'users:registration' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
        <input type="submit" value="Зарегистрироваться">
        </form>
    </div>
{% endblock %}